version: '3.6'
networks:
  development:
volumes:
  db_data:
  gem_cache:
  shared_data:
  node_modules:
  redis_data:
services:
  db:
    image: postgres:12.5-alpine
    container_name: wheel_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - development
    ports:
      - 5432
  redis:
    image: redis:6.2.3-alpine
    ports:
      - 6379
    volumes:
      - redis_data:/var/lib/redis/data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wheel_sidekiq
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/var/app/node_modules
    environment:
      RAILS_ENV: development
    entrypoint: docker-entrypoint.sh
    command: ['sidekiq']
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wheel_app
    image: wheel-dev:1.0.0
    volumes:
      - .:/var/app:cached
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/var/app/node_modules
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: docker-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
      PG_USER: postgres
      PG_PASSWORD: password
      PG_HOST: db
    depends_on:
      - db
      - redis
